name: co2-network
channels:
    - conda-forge
    - bioconda
dependencies:
    - python
    - pip

    - pre-commit
    - black

    - snakemake-minimal
    - graphviz

    - ipython
    - jupyter
    - jupyterlab

    - seaborn

    - pypsa>=0.21.3
    - atlite>=0.2.9
    - dask

    # Dependencies of the workflow itself
    - xlrd
    - openpyxl!=3.1.1
    - pycountry
    - seaborn
    - snakemake-minimal
    - memory_profiler
    - yaml
    - pytables
    - lxml
    - powerplantmatching>=0.5.5
    - numpy<1.24
    - pandas
    - geopandas>=0.11.0
    - rioxarray
    - xarray
    - netcdf4
    - networkx
    - scipy
    - shapely>=2.0
    - progressbar2
    - pyomo
    - matplotlib<3.6
    - proj
    - fiona
    - country_converter

    # Keep in conda environment when calling ipython
    - ipython

    # GIS dependencies:
    - cartopy
    - descartes
    - rasterio!=1.2.10

    # PyPSA-Eur-Sec Dependencies
    - geopy
    - tqdm
    - pytz
    - tabula-py
    - pyxlsb

    - pip:
        - vresutils>=0.3.1
        - tsam>=1.1.0
