name: co2-network
channels:
    - conda-forge
    - bioconda
dependencies:
    - python
    - pip
    
    - pre-commit
    - black

    - snakemake-minimal
    - graphviz

    - ipython
    - jupyter
    - jupyterlab
    
    
    # - pip:
    #     - ...
