scenarios:
  design:
    - co2network
    - noco2network
  sequestration:
    # - 0
    - 200
    - 400
    - 600
    - 800
    - 1000

labels:
  co2network: "with CO$_2$ network"
  noco2network: "without CO$_2$ network"
  carbon: "Captured Carbon"
  hydrogen: "Hydrogen"
  electricity: "Electricity"
  gas: "Natural Gas"
  co2: "Atmospheric CO$_2$"

constants:
  kinds:
    - electricity
    - gas
    - hydrogen
    - carbon
    - co2

  oneport_comps:
    - Generator
    - Store
    - StorageUnit
    - Load

  node_comps:
    - Generator
    - Link
    - StorageUnit
    - Load

  region_comps:
    - Store

  branch_comps:
    - Line
    - Link

  comps:
    - Generator
    - Store
    - StorageUnit
    - Line
    - Link

  sites:
    - residential urban decentral
    - services urban decentral
    - residential rural
    - services rural
    - services urban
    - urban central

  heating_techs:
    - heat
    - water tanks
    - solar thermal

  carrier_to_buses:
    carbon:
      - co2 stored
    hydrogen:
      - H2
    electricity:
      - AC
      - DC
      # - low voltage
    gas:
      - gas
    co2:
      - co2

  kind_to_carrier:
    electricity:
      production:
        Generator:
          - offwind
          - onwind
          - solar
          - ror
          - solar rooftop
        Link:
          bus1:
            - OCGT
            - H2 Fuel Cell
            - V2G
            - gas CHP
            - gas CHP CC
            - solid biomass CHP
            - solid biomass CHP CC
            - allam
            - battery discharger
            - home battery discharger
        StorageUnit:
          - PHS
          - hydro
      consumption:
        Load:
          - electricity
          - industry electricity
          - agriculture electricity
        Link:
          bus0:
            - H2 Electrolysis
            - battery charger
            - helmeth
            - BEV charger
            - ground heat pump
            - resistive heater
            - air heat pump
            - home battery charger
          bus2:
            - methanolisation
            - DAC
        StorageUnit:
          - PHS
          - hydro
      transport:
        Line:
          - AC
        Link:
          - DC
      storage:
        Store:
          - battery
          - home battery
        StorageUnit:
          - PHS
          - hydro

    gas:
      production:
        Generator:
          - gas
        Link:
          bus1:
            - Sabatier
            - helmeth
            - biogas to gas
            -  gas for industry
            -  gas for industry CC
      consumption:
        Load:
          - gas for industry
        Link:
          bus0:
            - OCGT
            - SMR CC
            - SMR
            - gas boiler
            - gas CHP
            - gas CHP CC
            - gas for industry
            - gas for industry CC
            - allam
      storage:
        Store:
          - gas
      transport:
        Link:
          - gas pipeline
          - gas pipeline new

    hydrogen:
      production:
        Link:
          bus1:
            - H2 Electrolysis
            - SMR CC
            - SMR
      consumption:
        Link:
          bus0:
            - H2 Fuel Cell
            - Sabatier
            - methanolisation
            - Fischer-Tropsch
        Load:
          - H2 for industry
          - H2 for shipping
          - land transport fuel cell
      storage:
        Store:
          - H2
      transport:
        Link:
          - H2 pipeline

    carbon:
      production:
        Link:
          bus1:
            - DAC
          bus2:
            - process emissions CC
            - allam
          bus3:
            - SMR CC
            - solid biomass for industry CC
            - gas for industry CC
          bus4:
            - gas CHP CC
            - solid biomass CHP CC
        Store:
          - co2 stored
      consumption:
        Link:
          bus2:
            - Sabatier
            - helmeth
            - Fischer-Tropsch
          bus3:
            - methanolisation
        Store:
          - co2 stored
      storage:
        Store:
          - co2 stored
      transport:
        Link:
          - CO2 pipeline

    co2:
      production:
        Load:
          - shipping methanol emissions
          - oil emissions
          - agriculture machinery oil emissions
        Link:
          bus1:
            - process emissions
            - process emissions CC
          bus2:
            - OCGT
            - SMR CC
            - SMR
            - gas boiler
            - gas for industry
            - gas for industry CC
          bus3:
            - gas CHP
            - gas CHP CC
      consumption:
        Link:
          bus0:
            - DAC
          bus2:
            - biogas to gas
            - solid biomass for industry CC
          bus3:
            - solid biomass CHP CC
      storage:
        Store:
          - co2

  # Watch out for negative efficiencies
  #                      'Sabatier', 'efficiency2'
  #                       'helmeth', 'efficiency2'
  #                 'biogas to gas', 'efficiency2'
  #          'solid biomass CHP CC', 'efficiency3'
  # 'solid biomass for industry CC', 'efficiency2'
  #               'methanolisation', 'efficiency2'
  #               'methanolisation', 'efficiency3'
  #               'Fischer-Tropsch', 'efficiency2'
  #                           'DAC', 'efficiency2'
  #                           'DAC', 'efficiency3'


plotting:
  theme:
    style: white
    context: paper
    font: serif
    rc:
      patch.linewidth: 0.1
      savefig.bbox: "tight"

  extent: [-12,  30,  35 ,  73]

  sequestration_map:
    figsize: [6,6]

  operation_area:
    figsize: [3, 3.5]

  operation_bar:
    figsize: [8, 10]

  cost_area:
    figsize: [7, 3]

  capacity_map:
    figsize: [10, 8]
    electricity:
      region_cmap: Greens
      region_unit: TWh
      bus_scale: 5e-6
      branch_scale: 2e-4
      bus_sizes:
        - 50000
        - 100000
      branch_sizes:
        - 5000
        - 10000
    gas:
      region_cmap: Purples
      region_unit: TWh
      bus_scale: 5e-7
      branch_scale: 5e-5
      bus_sizes:
        - 500000
        - 1000000
      branch_sizes:
        - 10000
        - 20000
    hydrogen:
      region_cmap: Blues
      region_unit: TWh
      bus_scale: 4e-5
      branch_scale: 2e-4
      bus_sizes:
        - 5000
        - 10000
      branch_sizes:
        - 5000
        - 10000
    carbon:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 1e-4
      branch_scale: 8e-4
      bus_sizes:
        - 5000
        - 10000
      branch_sizes:
        - 1000
        - 2000
    co2:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 1e-4
      branch_scale: 2e-3
      bus_sizes:
        - 5000
        - 10000
      branch_sizes:
        - 1000
        - 2000

  operation_map:
    figsize: [10, 8]
    electricity:
      region_cmap: Greens
      region_unit: TWh
      bus_scale: 4e-9
      branch_scale: 7e-9
      flow_scale: 6e-6
      bus_sizes:
        - 500 # TWh
        - 100 # TWh
      branch_sizes: null
    gas:
      region_cmap: Purples
      region_unit: TWh
      bus_scale: 1e-8
      branch_scale: 6e-8
      flow_scale: 3e-5
      bus_sizes:
        - 50 # TWh
        - 10 # TWh
      branch_sizes: null
    hydrogen:
      region_cmap: Blues
      region_unit: TWh
      bus_scale: 1e-8
      branch_scale: 3e-8
      flow_scale: 1e-5
      bus_sizes:
        - 100 # TWh
        - 50 # TWh
      branch_sizes: null
    carbon:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 2e-8
      branch_scale: 5e-8
      flow_scale: 2e-5
      bus_sizes:
        - 50 # Mt
        - 20 # Mt
      branch_sizes: null
    co2:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 8e-8
      branch_scale: 2e-7
      flow_scale: 8e-5
      bus_sizes:
        - 50 # Mt
        - 20 # Mt
      branch_sizes: null

  captureshare_line:
    figsize: [5, 4]

  technology_groups:
    AC: Electricity Grid
    Air Heat Pump: Heat Pump
    Allam Cycle: Carbon Capt. at Point Sources
    Battery: Battery Infrastructure
    Battery Charger: Battery Infrastructure
    Battery Discharger: Battery Infrastructure
    Bev Charger: Battery Infrastructure
    Biogas: Bioenergy
    Biogas To Gas: Bioenergy
    Biomass Boiler: Bioenergy
    "CO$_2$": CO$_2$ Infrastucture
    "CO$_2$ Pipeline": CO$_2$ Infrastucture
    "CO$_2$ Stored": CO$_2$ Infrastucture
    DAC: DAC
    DC: Electricity Grid
    Electricity Distribution Grid: Electricity Grid
    Fischer-Tropsch: Fischer-Tropsch
    Gas: Gas Infrastucture
    Gas Boiler: Gas Infrastucture
    Gas CHP: Gas Infrastucture
    "Gas CHP*": Carbon Capt. at Point Sources
    "Gas For Industry": Gas Infrastucture
    "Gas For Industry*": Carbon Capt. at Point Sources
    Ground Heat Pump: Heat Pump
    "H$_2$": H$_2$ Infrastucture
    "H$_2$ Electrolysis": H$_2$ Infrastucture
    "H$_2$ Fuel Cell": H$_2$ Infrastucture
    "H$_2$ Pipeline": H$_2$ Infrastucture
    Helmeth: Helmeth
    Home Battery: Battery Infrastructure
    Home Battery Charger: Battery Infrastructure
    Home Battery Discharger: Battery Infrastructure
    "Li Ion": Battery Infrastructure
    Methanol: Methanol
    Methanolisation: Methanolisation
    OCGT: Gas Infrastucture
    Offshore Wind: Wind
    Oil: Oil
    Onshore Wind: Wind
    Process Emissions: Process Emissions
    "Process Emissions*": Carbon Capt. at Point Sources
    Pumped Hydro Storage: Hydro Energy
    "Reservoir & Dam": Hydro Energy
    Resistive Heater: Resistive Heater
    "Run of River": Hydro Energy
    SMR: Hydrogen Infrastucture
    "SMR*": Carbon Capt. at Point Sources
    Sabatier: Sabatier
    Solar: Solar
    "Solar Rooftop": Solar
    "Solar Thermal": Solar
    "Solid Biomass": Bioenergy
    "Solid Biomass CHP": Bioenergy
    "Solid Biomass CHP*": Carbon Capt. at Point Sources
    "Solid Biomass For Industry": Bioenergy
    "Solid Biomass For Industry*": Carbon Capt. at Point Sources
    V2G: Battery Infrastructure
    "Water Tanks": Water Tanks
    "Water Tanks Charger": Water Tanks
    "Water Tanks Discharger": Water Tanks
  technology_group_colors:
    Hydro Energy: "#298c81"
    Battery Infrastructure: "#ace37f"
    Resistive Heater: "#d8f9b8"
    Methanolisation: "#57aac1"
    Water Tanks: "#e69487"
    Electricity Grid: "#97ad8c"
    CO$_2$ Infrastucture: "#cc99ff"
    Carbon Capt. at Point Sources: "#f29dae"
    Heat Pump: "#2fb537"
    Fischer-Tropsch: "#25c49a"
    DAC: "#ff5270"
    Bioenergy: "#baa741"
    H$_2$ Infrastucture: "#bf13a0"
    Gas Infrastucture: "#e05b09"
    Wind: "#66b5ff"
    Oil: "#001a33"
    Solar: "#ffe066"
    Process Emissions: '#222222'
