configs:
  test: 1
  presentation: 0

report:
  path: "report/submissions/ecemp/presentation/presentation"

remote:
  # ssh: zecm
  # path: /home/users/h/hofmann/scratch/projects/co2-network
  ssh: z1
  path: /home/htc/mhofmann/projects/co2-network

run:
  name: &runs
    - baseline
    - co2-only
    - h2-only
    - full

    - net-negative-0.05/baseline
    - net-negative-0.05/co2-only
    - net-negative-0.05/h2-only
    - net-negative-0.05/full

    - net-negative-0.1/baseline
    - net-negative-0.1/co2-only
    - net-negative-0.1/h2-only
    - net-negative-0.1/full

    - half-price/co2-only
    - half-price/full

  scenarios:
    enable: true
  shared_resources: true
  disable_progressbar: true

comparison:
  default:
    - baseline
    - co2-only
    - h2-only
    - full
  net-negative-0.05:
    - net-negative-0.05/baseline
    - net-negative-0.05/co2-only
    - net-negative-0.05/h2-only
    - net-negative-0.05/full
  net-negative-0.1:
    - net-negative-0.1/baseline
    - net-negative-0.1/co2-only
    - net-negative-0.1/h2-only
    - net-negative-0.1/full
  emission-reduction:
    - baseline
    - net-negative-0.05/baseline
    - net-negative-0.1/baseline
    - co2-only
    - net-negative-0.05/co2-only
    - net-negative-0.1/co2-only
    - h2-only
    - net-negative-0.05/h2-only
    - net-negative-0.1/h2-only
    - full
    - net-negative-0.05/full
    - net-negative-0.1/full
  subsidy:
    - baseline
    - half-price/co2-only
    - h2-only
    - half-price/full
  all: *runs
difference:
  default:
    - co2-only
    - h2-only
  net-negative-0.05:
    - net-negative-0.05/co2-only
    - net-negative-0.05/h2-only
  net-negative-0.1:
    - net-negative-0.1/co2-only
    - net-negative-0.1/h2-only
  emission-reduction-0.05-co2-only:
    - co2-only
    - net-negative-0.05/co2-only
  emission-reduction-0.05-h2-only:
    - h2-only
    - net-negative-0.05/h2-only
  emission-reduction-0.05-full:
    - full
    - net-negative-0.05/full
  emission-reduction-0.1-co2-only:
    - co2-only
    - net-negative-0.1/co2-only
  emission-reduction-0.1-h2-only:
    - h2-only
    - net-negative-0.1/h2-only
  emission-reduction-0.1-full:
    - full
    - net-negative-0.1/full


labels:
  baseline: "No CO$_2$ / H$_2$ Net"
  co2-only: "CO$_2$ Net Only"
  h2-only: "H$_2$ Net Only"
  full: "CO$_2$ & H$_2$ Net"

  half-price/co2-only: "Cheap CO$_2$ Net"
  half-price/full: "H$_2$ & Cheap CO$_2$ Net"

  net-negative-0.05/baseline: "No CO$_2$ / H$_2$ Net,\nNet-negative 5%"
  net-negative-0.05/co2-only: "CO$_2$ Net,\nNet-negative 5%"
  net-negative-0.05/h2-only: "H$_2$ Net,\nNet-negative 5%"
  net-negative-0.05/full: "CO$_2$ & H$_2$ Net,\nNet-negative 5%"

  net-negative-0.1/baseline: "No CO$_2$ / H$_2$ Net,\nNet-negative 10%"
  net-negative-0.1/co2-only: "CO$_2$ Net,\nNet-negative 10%"
  net-negative-0.1/h2-only: "H$_2$ Net,\nNet-negative 10%"
  net-negative-0.1/full: "CO$_2$ & H$_2$ Net,\nNet-negative 10%"

  net-neutral: "NN"
  net-negative-0.05: "NN 5%"
  net-negative-0.1: "NN 10%"

  carbon: "Captured Carbon"
  hydrogen: "Hydrogen"
  electricity: "Electricity"
  gas: "Natural Gas"
  co2: "Atmospheric CO$_2$"

constants:
  kinds:
    - electricity
    - gas
    - hydrogen
    - carbon
    - co2
  additional_kinds:
    - methanol
    - oil
    - heat

  oneport_comps:
    - Generator
    - Store
    - StorageUnit
    - Load

  node_comps:
    - Generator
    - Link
    - StorageUnit
    - Load

  region_comps:
    - Store

  branch_comps:
    - Line
    - Link

  comps:
    - Generator
    - Store
    - StorageUnit
    - Line
    - Link

  sites:
    - residential urban decentral
    - services urban decentral
    - residential rural
    - services rural
    - services urban
    - urban central

  heating_techs:
    - heat
    - water tanks
    - solar thermal

  carrier_to_buses:
    carbon:
      - co2 stored
      - co2 sequestered
    hydrogen:
      - H2
    electricity:
      - AC
      - DC
      # - low voltage
    gas:
      - gas
    co2:
      - co2


  kind_to_carrier:
    electricity:
      production:
        Generator:
          - offwind
          - onwind
          - solar
          - ror
          - solar rooftop
        Link:
          bus1:
            - OCGT
            - H2 Fuel Cell
            - V2G
            - gas CHP
            - gas CHP CC
            - solid biomass CHP
            - solid biomass CHP CC
            - allam
            - battery discharger
            - home battery discharger
        StorageUnit:
          - PHS
          - hydro
      consumption:
        Load:
          - electricity
          - industry electricity
          - agriculture electricity
        Link:
          bus0:
            - H2 Electrolysis
            - battery charger
            - BEV charger
            - ground heat pump
            - resistive heater
            - air heat pump
            - home battery charger
          bus2:
            - methanolisation
            - DAC
        StorageUnit:
          - PHS
          - hydro
      transport:
        Line:
          - AC
        Link:
          - DC
      storage:
        Store:
          - battery
          - home battery
        StorageUnit:
          - PHS
          - hydro

    gas:
      production:
        Generator:
          - gas
        Link:
          bus1:
            - Sabatier
            - biogas to gas
            - biogas to gas CC
            - gas for industry
            - gas for industry CC
      consumption:
        Load:
          - gas for industry
        Link:
          bus0:
            - OCGT
            - SMR CC
            - SMR
            - gas boiler
            - gas CHP
            - gas CHP CC
            - gas for industry
            - gas for industry CC
            - allam
      storage:
        Store:
          - gas
      transport:
        Link:
          - gas pipeline
          - gas pipeline new

    hydrogen:
      production:
        Link:
          bus1:
            - H2 Electrolysis
            - SMR CC
            - SMR
      consumption:
        Link:
          bus0:
            - H2 Fuel Cell
            - Sabatier
            - methanolisation
            - Fischer-Tropsch
        Load:
          - H2 for industry
          - land transport fuel cell
      storage:
        Store:
          - H2
      transport:
        Link:
          - H2 pipeline

    carbon:
      production:
        Link:
          bus1:
            - DAC
          bus2:
            - process emissions CC
            - allam
            - biogas to gas CC
          bus3:
            - SMR CC
            - solid biomass for industry CC
            - gas for industry CC
          bus4:
            - gas CHP CC
            - solid biomass CHP CC
        Store:
          - co2 stored
      consumption:
        Link:
          bus2:
            - Sabatier
            - Fischer-Tropsch
          bus3:
            - methanolisation
        Store:
          - co2 stored
          - co2 sequestered
      storage:
        Store:
          - co2 stored
          - co2 sequestered
      transport:
        Link:
          - CO2 pipeline

    co2:
      production:
        Load:
          - shipping methanol emissions
          - oil emissions
          - agriculture machinery oil emissions
        Link:
          bus1:
            - process emissions
            - process emissions CC
          bus2:
            - OCGT
            - SMR CC
            - SMR
            - gas boiler
            - gas for industry
            - gas for industry CC
          bus3:
            - gas CHP
            - gas CHP CC
        Store:
          - co2
      consumption:
        Link:
          bus0:
            - DAC
          bus2:
            - biogas to gas
            - solid biomass for industry CC
          bus3:
            - solid biomass CHP CC
            - biogas to gas CC
        Store:
          - co2
      storage:
        Store:
          - co2


plotting:
  theme:
    style: white
    context: paper
    font: sans-serif
    rc:
      patch.linewidth: 0.1
      savefig.bbox: "tight"

  extent: [-12,  30,  35 ,  73]

  sequestration_map:
    figsize: [6,6]

  energy_balance_bar:
    figsize: [4, 3.5]

  energy_balance_bar_wide:
    figsize: [10, 3.5]

  energy_balance_area:
    figsize: [8, 3.5]

  operation_bar:
    figsize: [10, 10]

  cost_bar:
    figsize: [4, 3]

  cost_bar_wide:
    figsize: [8, 3]

  objective_heatmap:
    figsize: [6, 6]

  cost_diff_bar:
    figsize: [5, 5]

  cost_diff_map:
    figsize: [10, 5]
    bus_scale: 0.5
    bus_sizes:
      - 5
      - 10

  capacity_country_bar:
    figsize: [5, 5]

  capacity_map:
    figsize: [10, 8]
    electricity:
      region_cmap: Greens
      region_unit: TWh
      bus_scale: 5e-6
      branch_scale: 2e-4
      bus_sizes:
        - 50000
        - 100000
      branch_sizes:
        - 5000
        - 10000
    gas:
      region_cmap: Purples
      region_unit: TWh
      bus_scale: 5e-7
      branch_scale: 5e-5
      bus_sizes:
        - 500000
        - 1000000
      branch_sizes:
        - 10000
        - 20000
    hydrogen:
      region_cmap: Blues
      region_unit: TWh
      bus_scale: 4e-5
      branch_scale: 2e-4
      bus_sizes:
        - 5000
        - 10000
      branch_sizes:
        - 5000
        - 10000
    carbon:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 1e-4
      branch_scale: 8e-4
      bus_sizes:
        - 5000
        - 10000
      branch_sizes:
        - 1000
        - 2000
    co2:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 1e-4
      branch_scale: 2e-3
      bus_sizes:
        - 5000
        - 10000
      branch_sizes:
        - 1000
        - 2000

  operation_map:
    figsize: [10, 8]
    electricity:
      region_cmap: Greens
      region_unit: TWh
      bus_scale: 4e-9
      branch_scale: 1e-8
      flow_scale: 8e-6
      bus_sizes:
        - 500 # TWh
        - 100 # TWh
      branch_sizes: null
    gas:
      region_cmap: Purples
      region_unit: TWh
      bus_scale: 1e-8
      branch_scale: 1e-8
      flow_scale: 4e-6
      bus_sizes:
        - 50 # TWh
        - 10 # TWh
      branch_sizes: null
    hydrogen:
      region_cmap: Blues
      region_unit: TWh
      bus_scale: 5e-9
      branch_scale: 1e-8
      flow_scale: 4e-6
      bus_sizes:
        - 100 # TWh
        - 50 # TWh
      branch_sizes: null
    carbon:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 2e-8
      branch_scale: 5e-8
      flow_scale: 7e-5
      bus_sizes:
        - 50 # Mt
        - 20 # Mt
      branch_sizes: null
    co2:
      region_cmap: Reds
      region_unit: Mt
      bus_scale: 8e-8
      branch_scale: 5e-7
      flow_scale: 2e-3
      bus_sizes:
        - 50 # Mt
        - 20 # Mt
      branch_sizes: null
    heat:
      region_cmap: Oranges
      region_unit: TWh
      bus_scale: 1e-8
      branch_scale: 1e-8
      flow_scale: 1e-5
      bus_sizes:
        - 100 # TWh
        - 50 # TWh
      branch_sizes: null
    methanol:
      region_cmap: Greens
      region_unit: TWh
      bus_scale: 1e-8
      branch_scale: 1e-8
      flow_scale: 1e-5
      bus_sizes:
        - 100 # TWh
        - 50 # TWh
      branch_sizes: null
    oil:
      region_cmap: Greys
      region_unit: TWh
      bus_scale: 1e-8
      branch_scale: 1e-8
      flow_scale: 1e-5
      bus_sizes:
        - 100 # TWh
        - 50 # TWh
      branch_sizes: null


  captureshare_line:
    figsize: [5, 2]

  technology_groups:
    AC: Electricity Grid
    BEV charger: Battery Infrastructure
    DAC: DAC
    DC: Electricity Grid
    Fischer-Tropsch: Fischer-Tropsch
    H2: H$_2$ Infrastucture
    H2 Electrolysis: H$_2$ Infrastucture
    H2 Fuel Cell: H$_2$ Infrastucture
    H2 Store: H$_2$ Infrastucture
    H2 for industry: H$_2$ Infrastucture
    H2 pipeline: H$_2$ Infrastucture
    Li ion: Battery Infrastructure
    OCGT: Gas Infrastucture
    PHS: Hydro Energy
    SMR: H$_2$ Infrastucture
    SMR CC: Carbon Capt. at Point Sources
    Sabatier: Other
    V2G: Battery Infrastructure
    agriculture electricity: Other
    agriculture heat: Other
    agriculture machinery oil: Other
    agriculture machinery oil emissions: Other
    air heat pump: Heat Pump
    allam: Carbon Capt. at Point Sources
    battery: Battery Infrastructure
    battery charger: Battery Infrastructure
    battery discharger: Battery Infrastructure
    battery storage: Battery Infrastructure
    biogas: Bioenergy
    biogas to gas: Bioenergy
    biogas to gas CC: Bioenergy
    biomass boiler: Bioenergy
    co2: CO$_2$ Infrastucture
    CO2 pipeline: CO$_2$ Infrastucture
    co2 sequestered: CO$_2$ Infrastucture
    co2 stored: CO$_2$ Infrastucture
    electricity: Electricity Grid
    electricity distribution grid: Electricity Grid
    gas: Gas Infrastucture
    gas pipeline: Gas Infrastucture
    gas pipeline new: Gas Infrastucture
    gas CHP: Gas Infrastucture
    gas CHP CC: Carbon Capt. at Point Sources
    gas boiler: Gas Infrastucture
    gas for industry: Gas Infrastucture
    gas for industry CC: Carbon Capt. at Point Sources
    geothermal: Other
    ground heat pump: Heat Pump
    heat: Other
    heat waste: Other
    home battery: Battery Infrastructure
    home battery charger: Battery Infrastructure
    home battery discharger: Battery Infrastructure
    hydro: Hydro Energy
    industry electricity: Other
    kerosene for aviation: Other
    land transport EV: Other
    land transport fuel cell: Other
    low voltage: Electricity Grid
    low-temperature heat for industry: Other
    methanol: Methanol
    methanolisation: Methanolisation
    naphtha for industry: Other
    offwind: Wind
    oil: Oil
    oil emissions: Other
    onwind: Wind
    other: Other
    process emissions: Process Emissions
    process emissions CC: Carbon Capt. at Point Sources
    resistive heater: Resistive Heater
    ror: Other
    shipping methanol: Shipping
    shipping methanol emissions: Shipping
    solar: Solar
    solar rooftop: Solar
    solar thermal: Solar
    solid biomass: Bioenergy
    solid biomass CHP: Bioenergy
    solid biomass CHP CC: Carbon Capt. at Point Sources
    solid biomass for industry: Bioenergy
    solid biomass for industry CC: Carbon Capt. at Point Sources
    water tanks: Water Tanks
    water tanks charger: Water Tanks
    water tanks discharger: Water Tanks
  technology_group_colors:
    Hydro Energy: "#298c81"
    Battery Infrastructure: "#ace37f"
    Resistive Heater: "#d8f9b8"
    Methanolisation: "#57aac1"
    Water Tanks: "#e69487"
    Electricity Grid: "#97ad8c"
    CO$_2$ Infrastucture: "#cc99ff"
    Carbon Capt. at Point Sources: "#f29dae"
    Heat Pump: "#2fb537"
    Fischer-Tropsch: "#25c49a"
    DAC: "#ff5270"
    Bioenergy: "#baa741"
    H$_2$ Infrastucture: "#bf13a0"
    Gas Infrastucture: "#e05b09"
    Shipping: "#ff8c00"
    Wind: "#66b5ff"
    Oil: "#001a33"
    Solar: "#ffe066"
    Process Emissions: '#222222'
    Other: '#aaaaaa'
