# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

baseline: {}

co2-only:
  sector:
    co2network: true

h2-only:
  sector:
    H2_network: true

full:
  sector:
    H2_network: true
    co2network: true

half-price/co2-only:
  sector:
    co2network: true
    co2_network_cost_factor: 0.5

half-price/full:
  sector:
    H2_network: true
    co2network: true
    co2_network_cost_factor: 0.5

net-negative-0.1/baseline:
  sector:
    co2_sequestration_potential: 661.4112
  co2_budget:
    2050: -0.1

net-negative-0.1/co2-only:
  sector:
    co2network: true
    co2_sequestration_potential: 661.4112
  co2_budget:
    2050: -0.1

net-negative-0.1/h2-only:
  sector:
    H2_network: true
    co2_sequestration_potential: 661.4112
  co2_budget:
    2050: -0.1

net-negative-0.1/full:
  sector:
    H2_network: true
    co2network: true
    co2_sequestration_potential: 661.4112
  co2_budget:
    2050: -0.1


# higher sequestration potential
seq-400/baseline:
  sector:
    co2_sequestration_potential: 400

seq-400/co2-only:
  sector:
    co2network: true
    co2_sequestration_potential: 400

seq-400/h2-only:
  sector:
    H2_network: true
    co2_sequestration_potential: 400

seq-400/full:
  sector:
    H2_network: true
    co2network: true
    co2_sequestration_potential: 400

seq-600/baseline:
  sector:
    co2_sequestration_potential: 600

seq-600/co2-only:
  sector:
    co2network: true
    co2_sequestration_potential: 600

seq-600/h2-only:
  sector:
    H2_network: true
    co2_sequestration_potential: 600

seq-600/full:
  sector:
    H2_network: true
    co2network: true
    co2_sequestration_potential: 600

seq-800/baseline:
  sector:
    co2_sequestration_potential: 800

seq-800/co2-only:
  sector:
    co2network: true
    co2_sequestration_potential: 800

seq-800/h2-only:
  sector:
    H2_network: true
    co2_sequestration_potential: 800

seq-800/full:
  sector:
    H2_network: true
    co2network: true
    co2_sequestration_potential: 800


# higher electrolysis costs
updated-electrolisys-capex/baseline:
  sector:
    hydrogen_electrolysis_cost_factor: 1.4

updated-electrolisys-capex/co2-only:
  sector:
    co2network: true
    hydrogen_electrolysis_cost_factor: 1.4

updated-electrolisys-capex/h2-only:
  sector:
    H2_network: true
    hydrogen_electrolysis_cost_factor: 1.4

updated-electrolisys-capex/full:
  sector:
    H2_network: true
    co2network: true
    hydrogen_electrolysis_cost_factor: 1.4


# # with fuel cell land transport eq. old setup

# w-fc/baseline:
#   sector:
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85

# w-fc/co2-only:
#   sector:
#     co2network: true
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85

# w-fc/h2-only:
#   sector:
#     H2_network: true
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85

# w-fc/full:
#   sector:
#     H2_network: true
#     co2network: true
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85

# w-fc/half-price/co2-only:
#   sector:
#     co2network: true
#     co2_network_cost_factor: 0.5
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85

# w-fc/half-price/full:
#   sector:
#     H2_network: true
#     co2network: true
#     co2_network_cost_factor: 0.5
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85

# w-fc/net-negative-0.1/baseline:
#   sector:
#     co2_sequestration_potential: 661.4112
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85
#   co2_budget:
#     2050: -0.1

# w-fc/net-negative-0.1/co2-only:
#   sector:
#     co2network: true
#     co2_sequestration_potential: 661.4112
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85
#   co2_budget:
#     2050: -0.1

# w-fc/net-negative-0.1/h2-only:
#   sector:
#     H2_network: true
#     co2_sequestration_potential: 661.4112
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85
#   co2_budget:
#     2050: -0.1

# w-fc/net-negative-0.1/full:
#   sector:
#     H2_network: true
#     co2network: true
#     co2_sequestration_potential: 661.4112
#     land_transport_fuel_cell_share:
#       2050: 0.15
#     land_transport_electric_share:
#       2050: 0.85
#   co2_budget:
#     2050: -0.1
