# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

half-price:
  sector:
    co2network: true
    co2_network_cost_factor: 0.5

projected-price:
  sector:
    co2network: true
    co2_network_cost_factor: 1.0

baseline:
  sector:
    co2network: false


nofossils:
  sector:
    co2network: true
    regional_co2_sequestration_potential:
      enable: false
    co2_sequestration_potential: 0
