# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

half-price:
  co2network: true
  co2_network_cost_factor: 0.5

projected-price:
  co2network: true
  co2_network_cost_factor: 1.0

baseline:
  co2network: false

# TESTING

test-half-price:
  co2network: true
  co2_network_cost_factor: 0.5

test-projected-price:
  co2network: true
  co2_network_cost_factor: 1.0

test-baseline:
  co2network: false
