# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

half-price:
  label: "With subsidized\nCO$_2$ Network"
  sector:
    co2network: true
    co2_network_cost_factor: 0.5

projected-price:
  label: "With\nCO$_2$ Network"
  sector:
    co2network: true
    co2_network_cost_factor: 1.0

baseline:
  label: "Without\nCO$_2$ Network"
  sector:
    co2network: false


no-h2-half-price:
  label: "With subsidized\nCO$_2$ Network and\nno H$_2$ Network"
  sector:
    H2_network: false
    co2network: true
    co2_network_cost_factor: 0.5

no-h2-projected-price:
  label: "With\nCO$_2$ Network and\nno H$_2$ Network"
  sector:
    H2_network: false
    co2network: true
    co2_network_cost_factor: 1.0

no-h2-baseline:
  label: "Without\nCO$_2$ Network and\nno H$_2$ Network"
  sector:
    H2_network: false
    co2network: false


no-waste-heat-half-price:
  label: "With subsidized\nCO$_2$ Network and\nno FT Waste Heat"
  sector:
    co2network: true
    co2_network_cost_factor: 0.5
    use_fischer_tropsch_waste_heat: false
    use_methanation_waste_heat: false
    use_methanolisation_waste_heat: false


no-waste-heat-projected-price:
  label: "With\nCO$_2$ Network and\nno FT Waste Heat"
  sector:
    co2network: true
    co2_network_cost_factor: 1.0
    use_fischer_tropsch_waste_heat: false
    use_methanation_waste_heat: false
    use_methanolisation_waste_heat: false

no-waste-heat-baseline:
  label: "Without\nCO$_2$ Network and\nno FT Waste Heat"
  sector:
    co2network: false
    use_fischer_tropsch_waste_heat: false
    use_methanation_waste_heat: false
    use_methanolisation_waste_heat: false
