# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

baseline: {}

co2-only:
  sector:
    co2network: true

h2-only:
  sector:
    H2_network: true

full:
  sector:
    H2_network: true
    co2network: true


half-price/co2-only:
  sector:
    co2network: true
    co2_network_cost_factor: 0.5


half-price/full:
  sector:
    H2_network: true
    co2network: true
    co2_network_cost_factor: 0.5


net-negative-0.05/baseline:
  sector:
    co2_sequestration_potential: 400
  co2_budget:
    2050: -0.05

net-negative-0.05/co2-only:
  sector:
    co2network: true
    co2_sequestration_potential: 400
  co2_budget:
    2050: -0.05

net-negative-0.05/h2-only:
  sector:
    H2_network: true
    co2_sequestration_potential: 400
  co2_budget:
    2050: -0.05

net-negative-0.05/full:
  sector:
    H2_network: true
    co2network: true
    co2_sequestration_potential: 400
  co2_budget:
    2050: -0.05

net-negative-0.1/baseline:
  sector:
    co2_sequestration_potential: 600
  co2_budget:
    2050: -0.1

net-negative-0.1/co2-only:
  sector:
    co2network: true
    co2_sequestration_potential: 600
  co2_budget:
    2050: -0.1

net-negative-0.1/h2-only:
  sector:
    H2_network: true
    co2_sequestration_potential: 600
  co2_budget:
    2050: -0.1

net-negative-0.1/full:
  sector:
    H2_network: true
    co2network: true
    co2_sequestration_potential: 600
  co2_budget:
    2050: -0.1
